version: '3.8'

services:
  app:
    build: .
    container_name: queue_app
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
      - ./target/classes:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes
    environment:
      - DB_URL=jdbc:postgresql://ep-plain-block-a1h9ffwn-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
      - DB_USER=neondb_owner
      - DB_PASS=npg_XexFlgN0WLd3